<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/** @var Mage_GoogleAnalytics_Block_Ga $this */
$_helper = $this->helper('googleanalytics');
?>
<?php if (!$this->helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php if ($_helper->isUseAnalytics4()): ?>
        <?php $_gaAccountId = $_helper->getAccountId() ?>
        <!-- BEGIN GOOGLE ANALYTICS 4 CODE -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=<?= $_gaAccountId ?>"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            <?php echo $this->_getPageTrackingCode($_gaAccountId) ?>
            <?php echo $this->_getEnhancedEcommerceDataForAnalytics4() ?>
        </script>
        <!-- END GOOGLE ANALYTICS 4 CODE -->
    <?php endif ?>
<?php endif ?>
